package com.jgbravo.moneymate.core.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal val LightThemeColors = lightColorScheme(
    primary = Color(ThemeColor.RoyalPurple),
    onPrimary = Color(ThemeColor.White),
    primaryContainer = Color(ThemeColor.Lavender),
    onPrimaryContainer = Color(ThemeColor.DeepViolet),
    secondary = Color(ThemeColor.BlackCoral),
    onSecondary = Color(ThemeColor.White),
    secondaryContainer = Color(ThemeColor.Lavender2),
    onSecondaryContainer = Color(ThemeColor.RaisinBlack),
    tertiary = Color(ThemeColor.DeepTaupe),
    onTertiary = Color(ThemeColor.White),
    tertiaryContainer = Color(ThemeColor.PiggyPink),
    onTertiaryContainer = Color(ThemeColor.DarkChocolate),
    error = Color(ThemeColor.Carnelian),
    errorContainer = Color(ThemeColor.PalePink),
    onError = Color(ThemeColor.White),
    onErrorContainer = Color(ThemeColor.SoftDarkChocolate),
    background = Color(ThemeColor.AlmostWhite),
    onBackground = Color(ThemeColor.AlmostWhite), //Color(ThemeColor.EerieBlack),
    surface = Color(ThemeColor.AlmostWhite),
    onSurface = Color(ThemeColor.EerieBlack),
    surfaceVariant = Color(ThemeColor.SoftPlatinum),
    onSurfaceVariant = Color(ThemeColor.DarkQuartz),
    outline = Color(ThemeColor.SonicSilver),
    inverseOnSurface = Color(ThemeColor.AntiFlashWhite),
    inverseSurface = Color(ThemeColor.DarkCharcoal),
    inversePrimary = Color(ThemeColor.LavenderBlue),
    surfaceTint = Color(ThemeColor.RoyalPurple),
    outlineVariant = Color(ThemeColor.LavenderGray),
    scrim = Color(ThemeColor.Black),
)

internal val DarkThemeColors = darkColorScheme(
    primary = Color(ThemeColor.LavenderBlue),
    onPrimary = Color(ThemeColor.PersianIndigo),
    primaryContainer = Color(ThemeColor.DarkSlateBlue),
    onPrimaryContainer = Color(ThemeColor.Lavender),
    secondary = Color(ThemeColor.LightPeriwinkle),
    onSecondary = Color(ThemeColor.VenetianRed),
    secondaryContainer = Color(ThemeColor.Quartz),
    onSecondaryContainer = Color(ThemeColor.Lavender2),
    tertiary = Color(ThemeColor.CameoPink),
    onTertiary = Color(ThemeColor.BrownCoffee),
    tertiaryContainer = Color(ThemeColor.DeepTuscanRed),
    onTertiaryContainer = Color(ThemeColor.PiggyPink),
    error = Color(ThemeColor.Melon),
    errorContainer = Color(ThemeColor.Sangria),
    onError = Color(ThemeColor.BloodRed),
    onErrorContainer = Color(ThemeColor.PalePink),
    background = Color(ThemeColor.EerieBlack),
    onBackground = Color(ThemeColor.Platinum),
    surface = Color(ThemeColor.EerieBlack),
    onSurface = Color(ThemeColor.Platinum),
    surfaceVariant = Color(ThemeColor.DarkQuartz),
    onSurfaceVariant = Color(ThemeColor.LavenderGray),
    outline = Color(ThemeColor.SpanishGray),
    inverseOnSurface = Color(ThemeColor.EerieBlack),
    inverseSurface = Color(ThemeColor.Platinum),
    inversePrimary = Color(ThemeColor.RoyalPurple),
    surfaceTint = Color(ThemeColor.LavenderBlue),
    outlineVariant = Color(ThemeColor.DarkQuartz),
    scrim = Color(ThemeColor.Black),
)